/**
 * Domain Craft Heuristics & Workshop Generator for Artified Nepal.
 * Tailored to Artified Nepal (Sahina Shrestha, Kathmandu, Nepal)
 * to automatically generate rich workshop descriptions, metadata, and WhatsApp messages.
 */

export interface AutoGeneratedWorkshopData {
  title: string;
  badge: string;
  tagline: string;
  description: string;
  keyTechniques: string[];
  suggestedAttendees: number;
  location: string;
  instructor: string;
  whatsappMessage: string;
  suggestedTags: string[];
}

export interface AutoGeneratedMediaCaption {
  title: string;
  caption: string;
  craftTechnique: string;
  tags: string[];
}

/**
 * Auto-generates workshop details, description, and metadata based on a topic / craft keyword.
 */
export function autoGenerateWorkshopGroup(rawTopic: string): AutoGeneratedWorkshopData {
  const topic = rawTopic.trim();
  const lower = topic.toLowerCase();

  let title = topic || 'Artisan Handcrafting Workshop';
  let badge = 'Workshop • Kathmandu Studio';
  let tagline = 'Hands-On Practical Training • Small Batch';
  let description = `Comprehensive practical workshop conducted by master artisan Sahina Shrestha in Kathmandu. Participants receive personalized step-by-step mentorship in authentic handcrafting technique, structural durability, and contemporary Nepali design.`;
  let keyTechniques = ['Material Preparation & Tensioning', 'Structural Core Assembly', 'Precision Locking Knots', 'Heirloom Finish & Sealing'];
  let suggestedTags = ['Kathmandu Artisans', 'Handmade in Nepal', 'Kathmandu Workshop', 'Sahina Shrestha'];

  if (lower.includes('macrame') || lower.includes('cord') || lower.includes('knot') || lower.includes('planter')) {
    title = topic.includes('Macrame') ? topic : `Macrame Handcrafting Workshop: ${topic}`;
    badge = 'Workshop • Macrame & Fiber Art';
    tagline = 'Cotton Cord Tensioning • Planters & Wall Art';
    description = `Intensive hands-on training focusing on raw cotton cord knotting, symmetrical tension, wooden hoop attachments, and botanical hanger architecture under Sahina Shrestha's guided mentorship in Kathmandu.`;
    keyTechniques = ['Larks Head & Square Knots', 'Continuous Spiral Knotting', 'Wooden Ring Planter Netting', 'Gathering Knot & Tassel Finish'];
    suggestedTags = ['Macrame Nepal', 'Cotton Knots', 'Plant Hangers', 'Kathmandu Craft'];
  } else if (lower.includes('sunflower') || lower.includes('waste') || lower.includes('pipe') || lower.includes('eco') || lower.includes('upcycling')) {
    title = topic.includes('Sunflower') || topic.includes('Waste') ? topic : `Eco-Upcycling Workshop: ${topic}`;
    badge = 'Workshop • Eco Sustainability & Botanical Craft';
    tagline = 'Waste to Art • Petal Sculpting & Ring Bases';
    description = `Transform discarded industrial waste pipes into vibrant, enduring floral art. Participants learn cylindrical ring sectioning, fabric petal creasing, multi-layer binding, and central seed texturing for sustainable botanical home accents.`;
    keyTechniques = ['Pipe Ring Sectioning', 'Fabric Petal Creasing & Binding', 'Multi-Layer Bloom Symmetry', 'Seed Core Texture Texturing'];
    suggestedTags = ['Eco Craft', 'Waste To Art', 'Upcycled Sunflowers', 'Sustainable Nepal'];
  } else if (lower.includes('pearl') || lower.includes('bead') || lower.includes('bag') || lower.includes('clutch') || lower.includes('jewelry')) {
    title = topic.includes('Pearl') ? topic : `Luxury Pearl Beading & Bag Workshop: ${topic}`;
    badge = 'Workshop • Couture Wearable Art';
    tagline = '8mm Pearl Cross-Weaving • Bridal Bag Architecture';
    description = `Specialized couture workshop exploring acrylic and glass pearl grid cross-weaving, reinforced monofilament tensioning, structural wall stabilization, and ergonomic handle wiring for bridal and evening accessories in Kathmandu.`;
    keyTechniques = ['4-Bead Cross-Weave Grid', 'Reinforced Internal Locking', 'Bag Corner Arch Geometry', 'Beaded Handle Load Balancing'];
    suggestedTags = ['Pearl Bags Nepal', 'Bridal Couture', 'Hand-Knotted Beads', 'Kathmandu Studio'];
  } else if (lower.includes('crochet') || lower.includes('yarn') || lower.includes('wool') || lower.includes('flower')) {
    title = topic.includes('Crochet') ? topic : `Artisan Crochet & Flower Crafting Workshop: ${topic}`;
    badge = 'Workshop • Fiber & Crochet Heritage';
    tagline = 'Petal Hook Work • Botanical Accessories';
    description = `Learn intricate crochet petal loops, stem wiring, and delicate flower charms. Participants create wearable floral brooches, hair ornaments, and customized bag charms using soft natural yarns.`;
    keyTechniques = ['Magic Ring & Petal Loops', 'Double Crochet Shaping', 'Floral Stem Wiring', 'Locking Stitch & Clean Ends'];
    suggestedTags = ['Crochet Nepal', 'Handmade Flowers', 'Yarn Art', 'Nepali Artisans'];
  } else if (lower.includes('dhaka') || lower.includes('weaving') || lower.includes('loom') || lower.includes('textile')) {
    title = topic.includes('Dhaka') ? topic : `Heritage Nepali Dhaka & Loom Weaving Workshop: ${topic}`;
    badge = 'Workshop • Nepali Heritage Weaving';
    tagline = 'Ancestral Loom Technique • Cultural Motifs';
    description = `Immerse in indigenous Nepali textile traditions. Master warp-and-weft balance, geometric diamond motifs, and sustainable natural dyeing under the guidance of traditional craftswomen.`;
    keyTechniques = ['Loom Warp Tensioning', 'Dhaka Geometric Motifs', 'Thread Shuttle Timing', 'Traditional Selvedge Finish'];
    suggestedTags = ['Dhaka Weaving', 'Nepali Heritage', 'Loom Craft', 'Ethical Fashion'];
  }

  const whatsappMessage = `Namaste Sahina Shrestha! ✨ I saw the "${title}" on your website and would love to register for the next training batch in Kathmandu.`;

  return {
    title,
    badge,
    tagline,
    description,
    keyTechniques,
    suggestedAttendees: 15,
    location: 'Kathmandu, Nepal',
    instructor: 'Sahina Shrestha',
    whatsappMessage,
    suggestedTags
  };
}

/**
 * Auto-generates captions, technique notes, and tags for uploaded workshop photos and videos.
 */
export function autoGenerateMediaCaption(filename: string, groupTitle = 'Artisan Workshop'): AutoGeneratedMediaCaption {
  const clean = filename.replace(/\.[^/.]+$/, '').replace(/[-_]/g, ' ');
  const lower = (clean + ' ' + groupTitle).toLowerCase();

  let title = `Hands-on Workshop Session: ${clean}`;
  let caption = `Practical demonstration during the workshop at Kathmandu, Nepal, guided step-by-step by Sahina Shrestha.`;
  let craftTechnique = 'Artisan Craft Mentorship';
  let tags = ['Kathmandu Workshop', 'Handmade in Nepal', 'Artisan Training'];

  if (lower.includes('macrame') || lower.includes('knot') || lower.includes('cord') || lower.includes('planter')) {
    title = `Macrame Cord Knotting & Loop Alignment (${clean})`;
    caption = `Overhead view of artisan cord tensioning and precision knotting taught by Sahina Shrestha to ensure long-lasting structural strength.`;
    craftTechnique = 'Macrame Tension & Knotting';
    tags = ['Macrame', 'Cord Tension', 'Handmade Nepal', clean];
  } else if (lower.includes('sunflower') || lower.includes('pipe') || lower.includes('waste') || lower.includes('eco')) {
    title = `Upcycled Waste Pipe to Sunflower Petal Craft (${clean})`;
    caption = `Step-by-step transformation of discarded pipes into bright, enduring sunflower petals with fabric wrapping and clean edge binding.`;
    craftTechnique = 'Pipe Ring & Petal Sculpting';
    tags = ['Eco Upcycling', 'Sunflowers', 'Waste to Art', clean];
  } else if (lower.includes('pearl') || lower.includes('bead') || lower.includes('bag')) {
    title = `Pearl Bag Cross-Weaving & Structural Beading (${clean})`;
    caption = `Precision hand-beading of acrylic pearls into rigid interlocking grids for evening bags and bridal couture.`;
    craftTechnique = 'Pearl Grid Cross-Weave';
    tags = ['Pearl Bag', 'Bridal Couture', 'Hand Knotted', clean];
  }

  return {
    title,
    caption,
    craftTechnique,
    tags
  };
}
